spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
      path: /h2-console/minimo

  datasource:
    url: jdbc:h2:mem:${LOCAL_H2_DB_NAME};DB_CLOSE_DELAY=-1
    username: ${LOCAL_H2_USER}
    password: ${LOCAL_H2_PASSWORD}
    driver-class-name: org.h2.Driver

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${LOCAL_KAKAO_CLIENT_ID}
            client-secret: ${LOCAL_KAKAO_CLIENT_SECRET}
            redirect-uri: ${LOCAL_KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_image
              - profile_nickname
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
minimo:
  jwt:
    secret-key: ${LOCAL_JWT_SECRET}
    access-token-expire-in: 1800
    refresh-token-expire-in: 1209600

logging:
  level:
    org.springframework.security: DEBUG