name: CD

on:
  workflow_run:
    workflows: ["CI"]  # CI 워크플로우 이름
    types:
      - completed  # CI 완료 후 실행

jobs:
  deploy:
    runs-on: ubuntu-latest  # 우분투 최신 환경에서 실행

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 코드 저장소 복제

      - name: Set up JDK 21
        uses: actions/setup-java@v3  # Java 21 설치

      - name: Build with Gradle
        run: ./gradlew clean build -x test  # JAR 빌드 (테스트 제외)

      - name: Create .env file
        run: |
          # GitHub Secrets에서 환경변수 가져와 .env 파일 생성
          echo "DEV_DB_HOST=${{ secrets.DEV_DB_HOST }}" >> .env
          echo "DEV_DB_PORT=${{ secrets.DEV_DB_PORT }}" >> .env
          echo "DEV_DB_NAME=${{ secrets.DEV_DB_NAME }}" >> .env
          echo "DEV_DB_USER=${{ secrets.DEV_DB_USER }}" >> .env
          echo "DEV_DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}" >> .env
          echo "DEV_JWT_SECRET=${{ secrets.DEV_JWT_SECRET }}" >> .env
          echo "DEV_KAKAO_CLIENT_ID=${{ secrets.DEV_KAKAO_CLIENT_ID }}" >> .env
          echo "DEV_KAKAO_CLIENT_SECRET=${{ secrets.DEV_KAKAO_CLIENT_SECRET }}" >> .env
          echo "DEV_KAKAO_REDIRECT_URI=${{ secrets.DEV_KAKAO_REDIRECT_URI }}" >> .env

      - name: Check JAR
        run: ls -l build/libs/  # JAR 파일 확인

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.5  # EC2로 JAR, .env 전송
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: |
            build/libs/*.jar
            .env
          target: /home/ubuntu/backend/

      - name: Restart backend service
        uses: appleboy/ssh-action@v0.1.7  # EC2에서 서비스 재시작
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            sudo systemctl daemon-reload       # systemd 적용
            sudo systemctl restart backend.service  # 서비스 재시작
            sudo systemctl status backend.service   # 상태 확인
